### ISSUE TITLE
중고매물 구입 비용 결정

### ISSUE THREAD

**Issue by swoohooh** [swoohooh/best-before#2]
**Describe `what` to do**
중고매물 구입을 위한 최소값과 최대값을 고민해보고 결정한다.

**Describe the expected outcome**
구입 최소값 ~ 최대값, 가격 선정 이유
e.g. 20,000 ~ 30,000, 이 가격대면 XX 브랜드까지 커버 할 수 있어서

**Describe `why` we need to do**
이 기준이 있어야 중고매물 구입이 가능하고, 수익을 예측해 볼 수 있다.

**Describe the expected `constraints` in doing this task**
중고 거래 시 택배비까지 같이 고민해보면 좋을듯

**Comment by hamzzi** [comment]
생각하는 최소 구입 가격은 가능하면 **한벌당 1만원 아래**라고 생각합니다.
저가 모델을 생각한다면 옷 한벌 비용이 택배비 정도와 유사해야 2회 대여시 손익분기에 도달할 수 있을 듯합니다.

90사이즈 남아옷 12벌 10,000원 https://cafe.naver.com/joonggonara/993241021
![image](https://github.com/swoohooh/carrot-digger/assets/24203536/37d679ed-3557-4393-972a-1879f02a0b50)

90사이즈 여아옷 9피스 24,000원 https://cafe.naver.com/joonggonara/993207755
![image](https://github.com/swoohooh/carrot-digger/assets/24203536/85f6ccc0-2dfd-49a6-a619-59d8af38d4d4)

90사이즈 여아옷 38,000원  https://cafe.naver.com/joonggonara/993103655
![image](https://github.com/swoohooh/carrot-digger/assets/24203536/76d6bee6-a112-496d-96fd-746efdbfbcac)
![image](https://github.com/swoohooh/carrot-digger/assets/24203536/e5f49f2a-24a9-4584-8396-6b35cf425b1c)
![image](https://github.com/swoohooh/carrot-digger/assets/24203536/e4e8fe66-b282-410e-b74a-dce8ddb66df5)
![image](https://github.com/swoohooh/carrot-digger/assets/24203536/f00afd6e-b0fe-42e7-a09e-31d3fa93f1d9)

**Comment by swoohooh** [comment]
아래 3개의 검토 결과를 조합해서 가격 결정 예정
- 설문조사 결과 해석
- #2 의 댓글 의견
- [코너마켓](https://www.cornermarket.co.kr/m2/) 제품들과의 가격 경쟁력

**Comment by swoohooh** [comment]
설문조사 기반으로 구독 서비스 비용 산정: 한달 / 5벌 / 3만원
손익 분기점이 너무 멀어서 서비스 변경 확정
