### ISSUE TITLE
서비스의 MVP 모습 고민(상상) 해오기

### ISSUE THREAD

**Issue by swoohooh** [swoohooh/best-before#4]
**Describe `what` to do**
우리가 하려는 서비스의 MVP(Minimum Viable Product)를 고민 해본다. 시장검증을 빠르게  해볼 수 있는 최소한의 기능단위를 정의해야 한다. 추가적으로 최소 기능단위로 구성 된 목업을 고민해 본다.

**Describe the expected outcome**
- 최소 기능
- 기능이 구현되는 platform
- use case
- mock-up

**Describe `why` we need to do**
설문조사와는 다른 방법으로 `실제` 시장검증이 가능하다.

**Describe the expected `constraints` in doing this task**
빨리, 효율적으로 해볼 수 있는 모든 방법 가능

**Due date**
2023-07-10

**Comment by hamzzi** [comment]
플랫폼
- 네이버 스마트스토어 / 인스타그램

Use case
- 물건 보여주기
- 결제
- 물품 발송/반송 이력 확인
- 히스토리 관리

**Comment by swoohooh** [comment]
- 서비스 플랫폼
	- Instagram 기업계정 구축
	- landing page
	- 네이버 스마트스토어 정기구독 판매
		- [정기구독 상품 설정하는 법](https://blog.naver.com/PostView.naver?blogId=fassto_official&logNo=222476421356&parentCategoryNo=&categoryNo=28&viewDate=&isShowPopularPosts=true&from=search)
- 요구되는 최소 기능
	- 서비스
		- 서비스 소개
		- 아이 옷 구독하기
		- 아이 옷 구독 취소하기
		- 구독 할 세부아이템(의류) 선택하기
			- 이 기능을 위해서는 자체 제작 사이트 필요 할 것으로 판단
		- 문의하기(CS)
	- 관리자
		- 구독자 목록 관리
		- 배송/반송 이력 확인하기
		- 구독자 데이터 분석(GA 연동)

**Comment by swoohooh** [comment]
개별 웹사이트를 구축하는 것으로 결정되었고, 그에 맞춰 요구되는 서비스 기능과 목업 필요

**Comment by swoohooh** [comment]
### 기능 요구사항
- 1. 홈페이지:
	- 로고와 서비스 소개를 포함한 메인 화면
	- 메뉴 또는 섹션으로 다른 페이지로 이동할 수 있는 네비게이션 바
	- 서비스 소개 섹션에는 아기 옷 구독 서비스의 장점과 특징을 간략하게 설명
- 2. 아이 옷 구독하기:
	- 구독 신청을 위한 페이지
	- 구독 계획(월별, 분기별, 반년별 등)과 가격 옵션
	- 아이의 나이와 성별 선택
	- 필요한 옷의 종류나 스타일 등의 기준을 설정할 수 있는 필터 또는 체크박스
	- 결제 하기(e.g. 네이버 페이)
- 3. 구독 할 세부 아이템(의류) 선택하기 (option):
	- 아이 옷 구독 상세 페이지
	- 구독자가 세부 아이템(의류)을 선택할 수 있는 옵션 표시
	- 각 아이템에 대한 설명, 사진, 가격 표시
	- 선택한 아이템의 총 가격 계산
- 4. 아이 옷 구독 상태 보기:
	- 구독자 개인 페이지 또는 대시보드
	- 구독 상태(활성, 일시정지, 종료 등) 표시
	- 현재 보유 중인 옷의 종류와 수량 표시
	- 다음 배송 예정일 표시
	- 배송 상태 확인 기능
- 5. 아이 옷 구독 취소하기:
	- 구독을 취소하는 페이지
	- 구독자의 식별을 위한 정보(이름, 이메일, 구독 번호 등) 입력란
	- 취소 사유를 선택하는 드롭다운 메뉴 또는 텍스트 입력란
- 6. 문의하기 (고객 서비스):
	- 문의를 위한 고객 서비스 페이지 또는 연락처 제공
	- 이메일 양식 또는 메시지 입력란
	- 문의 유형(일반 문의, 기술 지원, 불편 사항 보고 등) 선택
- 7. 관리자:
	- 관리자 로그인 페이지
	- 구독자 목록을 확인하고 관리할 수 있는 대시보드
	- 구독자의 개인 정보(이름, 이메일, 구독 상태 등) 표시
	- 배송/반송 이력 확인을 위한 페이지 또는 섹션
	- Google Analytics(GA)와의 연동을 통한 구독자 데이터 분석 페이지

**Comment by swoohooh** [comment]
- references:
  - https://vercel.com/templates/next.js/medusa
  - https://vercel.com/templates/next.js/subscription-starter
  - https://vercel.com/templates/next.js/nextjs-commerce
  - https://github.com/kirill-zhirnov/boundless-nextjs-ecommerce-template
- 홈페이지
<img width="137" alt="Screenshot 2023-07-16 at 8 15 55 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/c89419e7-6e79-46d3-9628-960c383dac6e">

- 아이 옷 구독하기
<img width="354" alt="Screenshot 2023-07-16 at 8 18 46 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/1374fd64-9d94-4106-b32b-fc105bbd248f">


- 구독 할 세부 아이템 선택하기
<img width="419" alt="Screenshot 2023-07-16 at 8 21 28 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/fa09af29-5deb-4108-8a8a-febdf9809144">

<img width="196" alt="Screenshot 2023-07-16 at 8 22 18 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/20777675-0421-4d35-996a-61c516fa4a2a">

**Comment by swoohooh** [comment]
### static page로 mockup 구성
https://github.com/swoohooh/carrot-digger/tree/mockup-nextjs

### 세부 페이지
<img width="1423" alt="Screenshot 2023-07-16 at 10 06 26 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/88ec99b3-b2b4-49cb-ad23-cd7c43644f5d">

<img width="1436" alt="Screenshot 2023-07-16 at 10 06 42 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/6ab7e456-a1c4-4b31-b51d-d72ddd966bf8">

<img width="1435" alt="Screenshot 2023-07-16 at 10 06 52 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/d45743a2-388c-4e2f-9ad1-b9a1670a0fca">

<img width="1012" alt="Screenshot 2023-07-16 at 10 07 10 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/ea29b9f3-a0ea-4585-81fd-03ae668ef84f">

<img width="1279" alt="Screenshot 2023-07-16 at 10 07 22 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/863cd060-7f9b-4f4d-942c-63e2ba83d3fd">

<img width="1324" alt="Screenshot 2023-07-16 at 10 07 40 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/87aba7c3-f3a5-48e3-ac3c-977566ab0269">

<img width="717" alt="Screenshot 2023-07-16 at 10 07 58 PM" src="https://github.com/swoohooh/carrot-digger/assets/58333547/9ec74c4e-e9d5-4840-ab8f-1e49a9d35dc8">
