### ISSUE TITLE
서비스 Use Case 정의하기

### ISSUE THREAD

**Issue by swoohooh** [swoohooh/best-before#6]
**Describe `what` to do**
best before 서비스의 사용자 정의(페르소나)를 하고, Use Case 를 확정한다.

**Describe the expected outcome**
아래 3가지 결과물. 결과는 아래 예시와 똑같지 않아도 괜찮음.

- 사용자 페르소나
  - https://marketsplash.com/ko/best-persona-examples-templates/
- Use Case (text)
  - <img width="744" alt="Screenshot 2023-08-06 at 6 59 32 PM" src="https://github.com/swoohooh/best-before/assets/58333547/9f5bf23d-38d0-40de-b437-2808b080e595">
- Use Case Diagram
  - <img width="777" alt="Screenshot 2023-08-06 at 6 58 24 PM" src="https://github.com/swoohooh/best-before/assets/58333547/dcf8a709-6d19-4841-b575-b55faa9f4c00">

**Describe `why` we need to do**
Mock-up 을 시작하기 전에 정확한 사용자를 타겟해서 필요한 사용자의 시나리오를 정의하는데 도움을 줄 수 있다.

**Describe the expected `constraints` in doing this task**

** Due date
2023-08-08

**Comment by swoohooh** [comment]
## Use Case Diagram
![image](https://github.com/swoohooh/best-before/assets/58333547/c5e993fa-0797-4c72-84c3-406d5db3d1a0)

**Comment by swoohooh** [comment]
## Use Case 시나리오

### [식단 계획하기]
<details>
  <summary>Click me</summary>

- overview
	- 식단 계획하기 버튼을 누르면 내가 정한 기간동안 식단을 계획 할 수 있게 도와준다. 식단 계획하기 에서는 이미 메뉴들이 모두 들어있고, 간단한 터치만으로 장보기 전 먹을 식단을 쉽게 계획할 수 있게 도와준다.
- relationships
	- initiator: 사용자
	- supporters:
	- pre-condition:
	- post-condition: 사용자가 계획한 식단이 저장된다. 사용자가 계획한 식단에 따른 장보기 목록이 작성된다.
- basic flow
	- 식단 계획하기 버튼을 누른다.
	- 식단을 계획할 일자를 입력한다.
	- 오늘부터 식단을 계획할 일자까지 하이라이트 처리 된 달력이 생성된다.
	- 하이라이트 된 날짜를 누르면 메뉴 선택 화면으로 이동한다.
	- 맨 상단에는 fuzz search 가 가능한 검색창이 있고, 검색을 하지않았을 때 기본적으로 추천 메뉴들이 뜬다.
	- 메뉴를 눌러서 누른 날짜의 식단을 계획한다.
	- 모든 날짜에 대해서 반복 수행한다.
	- 계획 완료하기 버튼을 누른다.
	- 계획한 식단과 사용자가 계획한 식단에 다른 장보기 목록을 등록한 후 등록한 식단을 보여준다.
- alternative flow
	- 검색
		- fuzz search 검색이 가능한 검색 창에 검색어를 입력한다.
		- 검색어의 일치도 기반으로 아래 창에 메뉴가 나온다.
		- basic flow 메뉴를 눌러서 누른 날짜의 식단을 계획한다로 이동
- error flow
	- 계획 한 식단이 존재하는 경우
		- 이미 계획 한 식단이 존재한다고 토스트 박스로 알려준다.
	- 식단 계획 일자를 너무 허용 값을 넘는 범위로 입력했을 경우
		- 계획 일자가 잘못 됐다고 토스트 박스로 알려주고, 기본 값을 7일로 바꾼다.
	- 계획하지 않은 날짜가 존재하는 경우
		- 계획 완료하기 버튼 눌렀을 시, 계획하지 않은 날짜가 존재한다고 알려주고 아무 일도 일어나지 않는다.
</details>

### [식단 목록보기]
<details>
  <summary>Click me</summary>

- overview
	- 내가 계획한 식단의 목록을 보여준다. 달력에 날짜별로 메뉴 이름과 메뉴 아이콘이 나올 수 있게 한다.
- relationships
	- initiator: 사용자
	- supporters:
	- pre-condition: 식단 계획하기가 완료 된 상태여야 한다.
	- post-condition:
- basic flow
	- 식단 목록 보기 버튼을 누른다.
	- 오늘부터 식단을 계획할 일자까지 하이라이트 처리 된 달력이 생성된다.
	- 하이라이트 처리 된 곳에는 식단 이름, 식단 아이콘이 표시되어 있다.
	- 날짜를 누르면 그 날의 식단을 자세히 볼 수 있다. 그 날 식단의 이름과 그것을 만드는데 들어가는 (재료이름, 재료 사용량) 이 표시되어 있다.
- alternative flow
- error flow
</details>

### [장보기 목록 보기]
<details>
  <summary>Click me</summary>

- overview
	- 내가 계획한 식단에 따른 장보기 목록을 보여준다. 기본적으로 내가 계획한 식단을 기반으로 식재료 목록 및 식재료양을 보여준다. 하지만 이전에 장보기, 식단 준비 한 후 남은 재료가 있다면 그것을 제외하고 보여준다.
- relationships
	- initiator: 사용자
	- supporters:
	- pre-condition: 식단 계획하기가 완료 된 상태여야 한다.
	- post-condition:
- basic flow
	- 장보기 목록 보기 버튼을 누른다.
	- 구매해야 하는 식재료 목록이 보인다.
	- 목록의 한 줄에는 (식재료 이름, 구매할 양, 필요한 양 - 남은 양) 과 같은 포맷으로 정보를 보여준다.
	- 구매할 양이 0인 구매할 필요 없는 식재료 이름은 회색으로 표시한다.
- alternative flow
- error flow
</details>

### [식재료 소비기한 입력]
<details>
  <summary>Click me</summary>

- overview
	- 장보기를 마친 식재료를 입력할 수 있다. (영수증 촬영, 바코드 입력, 직접 입력) 의 방법으로 구매한 식재료를 입력할 수 있으며, 입력한 정보를 바탕으로 식재료의 소비기한을 관리해준다.
- relationships
	- initiator: 사용자
	- supporters:
	- pre-condition: 식단 계획하기가 완료 된 상태여야 한다. 그를 바탕으로 장을 봐온 후이다.
	- post-condition: 사용자가 구매한 식재료가 입력된다. 식재료 별로 소비기한이 관리된다.
- basic flow
	- 식재료 소비기한 입력 버튼을 누른다.
	- 카메라의 촬영 모드가 활성화 된다.
	- 구매해 온 영수증을 촬영한다.
	- 영수증을 인식한 목록을 보여주며 수정이 가능하게 해준다.
	- 완료버튼을 누른다.
	- 식재료가 등록되며, 식재료 소비기한을 볼 수 있는 페이지로 이동한다.
- alternative flow
	- 바코드 입력
		- 카메라의 촬영 모드가 활성화 된다.
		- 제품의 바코드를 촬영한다.
		- 1-2 과정을 모든 제품에 반복한다.
		- 인식한 목록을 보여주며 수정이 가능하게 해준다.
		- basic flow 완료버튼을 누른다로 이동
	- 직접 입력
		- 식재료를 입력할 수 있는 form 이 뜬다.
		- 식재료의 이름과 수량을 입력한다.
		- 1-2 과정을 모든 제품에 반복한다.
		- 인식한 목록을 보여주며 수정이 가능하게 해준다.
		- basic flow 완료버튼을 누른다로 이동
- error flow
	- 영수증 인식 불가
		- 영수증이 인식되지 않는다는 메세지를 보여주고, 다시 촬영모드로 돌아간다.
	- 바코드 인식 불가
		- 바코드가 인식되지 않는다는 메세지를 보여주고, 다시 촬영모드로 돌아간다.
	- 직접 입력 내용이 모두 입력되지 않았을 때
		- 내용이 입력되지 않았을 때 입력 박스가 빨간 테두리로 바뀌며, 완료 버튼이 비활성화 된다.
</details>

### [사용자 별 하루 앱 이용 시간]
<details>
  <summary>Click me</summary>

- overview
	- 사용자 별로 하루 앱 이용 시간을 볼 수 있는 페이지를 제공한다.
- relationships
	- initiator: 관리자
	- supporters: GooglePlay & AppleStore
	- pre-condition: market 에 앱이 등록되어 있어야 한다.
	- post-condition:
- basic flow
	- 날짜를 선택할 수 있는 select box 가 뜬다.
	- 날짜를 선택하면, (사용자 이름, 하루 앱 이용시간) row를 가지는 table 이 뜨며 이용시간으로 내림차순 정렬되어서 보인다.
- alternative flow
- error flow
</details>

### [하루 접속 사용자수]
<details>
  <summary>Click me</summary>

- overview
	- 일별 접속 사용자수를 보여주는 페이지를 제공한다. 월을 선택하면, 일별 접속 사용자수가 막대 그래프로 보이게끔 구성한다.
- relationships
	- initiator: 관리자
	- supporters: GooglePlay & AppleStore
	- pre-condition: market 에 앱이 등록되어 있어야 한다.
	- post-condition:
- basic flow
	- 월을 선택할 수 있는 select box 가 뜬다.
	- 월을 선택하면 일별로 사용자 수를 막대 그래프로 보여준다.
- alternative flow
- error flow
</details>

### [영수증 인식 확인]
<details>
  <summary>Click me</summary>

- overview
	- 사용자가 입력시킨 영수증 사진과 영수증이 OCR 로 인식된 결과, 사용자가 수정한 결과를 비교할 수 있는 페이지를 보여준다.
- relationships
	- initiator: 관리자
	- supporters: OCR
	- pre-condition: 사용자가 영수증 촬영 기능을 수행했어야 한다.
	- post-condition:
- basic flow
	- 날짜를 선택할 수 있는 select box 가 뜬다.
	- 날짜를 선택하면 오늘 촬영해서 등록 된 영수증 목록이 날짜 내림차순으로 보인다.
	- 영수증 목록에서 한개의 항목을 선택하면 자세히 보기 페이지로 간다.
	- 자세기 보기 페이지에서는 (영수증 사진, OCR 인식 결과, 사용자가 수정한 결과) 를 비교해서 볼 수 있게 보여준다.
- alternative flow
- error flow
</details>

### [장보기 랭킹 확인]
<details>
  <summary>Click me</summary>

- overview
	- 장보기 한 식재료들 중 구매 순위가 높은 목록을 랭킹으로 보여준다.
- relationships
	- initiator: 관리자
	- supporters: better-before API
	- pre-condition: 사용자가 식재료 소비기한 입력 기능을 사용해야 한다.
	- post-condition:
- basic flow
	- 일을 선택할 수 있는 select box 가 뜬다.
	- 일을 선택하면 식재료 별로 구매 수를 막대 그래프로 보여준다.
- alternative flow
- error flow
</details>

**Comment by hamzzi** [comment]
냉장고 내 재료로 요리 가능한 식단도 볼 수 있으면 좋겠습니다.
지금 use case는 계획->구매->관리 형태로 진행되지만 구매 이후 식단을 구성하는 use case도 고려가 필요합니다.

**Comment by swoohooh** [comment]
> 냉장고 내 재료로 요리 가능한 식단도 볼 수 있으면 좋겠습니다.
> 지금 use case는 계획->구매->관리 형태로 진행되지만 구매 이후 식단을 구성하는 use case도 고려가 필요합니다.

제가 잘 이해 못한 부분이 두 군데가 있습니다.
1. 이미 계획을 하고 구매를 했는데 굳이 구매 이후에 다시 식단을 구성하게 도와줘야 할 이유가 있을까요? 만약 계획 한 식단이 다 끝난 상태이고 냉장고 내 재료로 요리를 해야하는 상황이라면 계획을 다시 세우는 use case 로 다시 돌아가면 되는거 아닌가요?
2. 만약 이렇게 중간에 기능을 지원하게 되면 저희가 고려했던 음식 구매 & 소비 사이클을 어떤식으로 가져가면 될까요?

@hamzzi 의견 부탁드립니다.

**Comment by swoohooh** [comment]
## 유저 페르소나

### 조사하면서 생긴 문제점
- 처음 유저 페르소나를 작성하려던 이유는 타겟 사용자를 명확하게 표현해 각 타겟 사용자마다 문제점을 확인하여 다각적인 기획을 하려던 목표였음
- 하지만 구매자, 마케팅 페르소나는 일반 사용자를 인터뷰, 테스트 및 분석하는 동안 수신한 **데이터를 기반**으로 구성해야 한다고 함
- 일단 상상으로 **타겟 사용자를 정의**하는 수준으로 만들어 볼 예정

### 결과물
<img width="501" alt="Screenshot 2023-08-26 at 4 11 13 PM" src="https://github.com/swoohooh/best-before/assets/58333547/1e6a1b09-d4ed-4f8f-b15b-658acf407ff3">
<img width="660" alt="Screenshot 2023-08-26 at 5 14 02 PM" src="https://github.com/swoohooh/best-before/assets/58333547/c9e2cc42-f2af-4d20-8be2-1c32d621dce9">
<img width="481" alt="Screenshot 2023-08-26 at 5 23 17 PM" src="https://github.com/swoohooh/best-before/assets/58333547/133ffcec-7889-4dd4-9a76-ff6e78450c69">
<img width="556" alt="Screenshot 2023-08-26 at 5 28 09 PM" src="https://github.com/swoohooh/best-before/assets/58333547/5c6507bf-90cc-4560-a51a-1cfe948fe3f5">

**Comment by swoohooh** [comment]
@hamzzi 
- Use Case 리뷰 부탁드립니다.
- 페르소나에 적은 사용자 중에 타겟 고객을 선정 부탁드립니다.
  (없으면 기대하는 타겟층을 글로 간단하게 남겨주세요)

**Comment by hamzzi** [comment]
> > 냉장고 내 재료로 요리 가능한 식단도 볼 수 있으면 좋겠습니다.
> > 지금 use case는 계획->구매->관리 형태로 진행되지만 구매 이후 식단을 구성하는 use case도 고려가 필요합니다.
> 
> 제가 잘 이해 못한 부분이 두 군데가 있습니다.
> 
> 1. 이미 계획을 하고 구매를 했는데 굳이 구매 이후에 다시 식단을 구성하게 도와줘야 할 이유가 있을까요? 만약 계획 한 식단이 다 끝난 상태이고 냉장고 내 재료로 요리를 해야하는 상황이라면 계획을 다시 세우는 use case 로 다시 돌아가면 되는거 아닌가요?
> 2. 만약 이렇게 중간에 기능을 지원하게 되면 저희가 고려했던 음식 구매 & 소비 사이클을 어떤식으로 가져가면 될까요?
> 
> @hamzzi 의견 부탁드립니다.

계획이 언제든 바뀔 수 있지 않을까요? 없던 식사 계획이 생길 수도 있고 외식이 생겨서 식사를 안할 수도 있을 듯 하여 이런 경우에 계획과 집행에 차이가 생길 수 있을 듯 합니다. 계획 했던 식사를 하기 싫을 경우도 있을 수 있고요

**Comment by hamzzi** [comment]
> @hamzzi
> 
> * Use Case 리뷰 부탁드립니다.
> * 페르소나에 적은 사용자 중에 타겟 고객을 선정 부탁드립니다.
>   (없으면 기대하는 타겟층을 글로 간단하게 남겨주세요)

페르소나가 직업군으로 대표되는 느낌이 드는데 의도하신걸까요?
일단 제가 타겟팅 한 느낌은 전업주부에 가깝긴 했습니다.

**Comment by swoohooh** [comment]
> > > 냉장고 내 재료로 요리 가능한 식단도 볼 수 있으면 좋겠습니다.
> > > 지금 use case는 계획->구매->관리 형태로 진행되지만 구매 이후 식단을 구성하는 use case도 고려가 필요합니다.
> > 
> > 
> > 제가 잘 이해 못한 부분이 두 군데가 있습니다.
> > 
> > 1. 이미 계획을 하고 구매를 했는데 굳이 구매 이후에 다시 식단을 구성하게 도와줘야 할 이유가 있을까요? 만약 계획 한 식단이 다 끝난 상태이고 냉장고 내 재료로 요리를 해야하는 상황이라면 계획을 다시 세우는 use case 로 다시 돌아가면 되는거 아닌가요?
> > 2. 만약 이렇게 중간에 기능을 지원하게 되면 저희가 고려했던 음식 구매 & 소비 사이클을 어떤식으로 가져가면 될까요?
> > 
> > @hamzzi 의견 부탁드립니다.
> 
> 계획이 언제든 바뀔 수 있지 않을까요? 없던 식사 계획이 생길 수도 있고 외식이 생겨서 식사를 안할 수도 있을 듯 하여 이런 경우에 계획과 집행에 차이가 생길 수 있을 듯 합니다. 계획 했던 식사를 하기 싫을 경우도 있을 수 있고요

그것까지 고려해서 나중에 기획을 바꿔야겠네요. 일단 지금은 무조건 식단 계획이 필요한데, 그 부분을 옵션으로 바꾸고 나머지는 그대로 진행해보시죠.

**Comment by swoohooh** [comment]
> > @hamzzi
> > 
> > * Use Case 리뷰 부탁드립니다.
> > * 페르소나에 적은 사용자 중에 타겟 고객을 선정 부탁드립니다.
> >   (없으면 기대하는 타겟층을 글로 간단하게 남겨주세요)
> 
> 페르소나가 직업군으로 대표되는 느낌이 드는데 의도하신걸까요? 일단 제가 타겟팅 한 느낌은 전업주부에 가깝긴 했습니다.

직업군을 대표하게 의도한건 아니었습니다. 그냥 페르소나 작성할 때 저런 요소를 넣어야 사용자에 대해서 제대로 이해하고 기획을 할 수 있다고해서 따라해봤습니다.

제 생각으로 전업주부는 매일 요리를 하고 식재료 관리가 항상 머리속에 있어서, 비 정기적으로 요리하는 신혼부부나 자취하는 대학생이나 직장인이 타겟으로 적당하지 않을까 생각했었습니다.
일단 `전업주부`, `신혼부부` 를 대상으로 하는 방향으로 하시죠
