### ISSUE TITLE
경쟁 제품 조사

### ISSUE THREAD

**Issue by swoohooh** [swoohooh/best-before#7]
**Describe `what` to do**
현재까지 정해진 내용을 기반으로 경쟁 제품을 조사한다.

- problems
	- 식재료의 구입 시기와 제품 별 소비기한을 모르기 때문에 상해서 버리게 되는 문제 발생
- key ideas
	- [식단 계획, 식재료 구매, 식재료 소비] 사이클 기반으로 식재료의 in-out 을 관리하고 유기적으로 소비기한 관리
- features
	- 일주일 식단 선택
	- 장보기 리스트 제공
	- 장 본 재료 소비기한 관리

**Describe the expected outcome**
- 경쟁 제품 특징 요약
- 경쟁 제품 **요약**할 수 있는 하나의 **표**

**Describe `why` we need to do**
- 우리 기획의 당위성 확보
- 차별점 있는 핵심 기능 발굴

**Describe the expected `constraints` in doing this task**
약간 조사하다보니 iOS에 만 존재하는 앱들이 있어서 실행해보지 못할 것 같음

**Dute date
2023-08-11

**Comment by hamzzi** [comment]
[밥타임라는 어플 없어졌나요?](https://www.82cook.com/entiz/read.php?bn=15&num=3224385)
없어져서 속상하다는 짧은 내용이지만 어플의 주 기능은 식재료를 입력해두면 가능한 요리 레시피를 알려주는 거라고 합니다.

**Comment by hamzzi** [comment]
- 유통기한 언제지
https://play.google.com/store/apps/details?id=kr.co.ourneeds.app&pcampaignid=web_share
유통기한 등록, 유통기한 알림, 냉장고 공유, 냉장고 추가

- 윈더 프리지
https://play.google.com/store/apps/details?id=com.meolly.fridge&pcampaignid=web_share
식품 추가, 장보기 목록

- 만개의레시피
https://play.google.com/store/apps/details?id=com.ezhld.recipe&pcampaignid=web_share
냉장고 파먹기, 오늘 뭐먹지, 레시피, 요리후기, 핫딜 쇼핑, 

- Whisk
https://play.google.com/store/apps/details?id=com.foodient.whisk&pcampaignid=web_share
레시피 저장, 식단, 쇼핑 목록, 레시피 공유

**Comment by swoohooh** [comment]
## 경쟁 제품 특징 요약
가장 다운로드가 많은 앱부터 순서

### **BEEP**
- stores
	- iOS - 4.7 / 457개
	- android - 3.8 / 1천개 / 50만회 이상
- 임박상품
	- 모든 상품들을 유통기한이 얼마 남지 않은 순으로 정렬
- 카테고리
	- 개인이 카테고리 추가 가능
- 상품 추가
	- 바코드 스캔 (유동기한 수동입력)
	- 사진 촬영
	- 직접 입력
- 멤버 추가
### **유통기한 언제지** - 가장 쉬운 냉장고 관리
- stores
	- iOS - 4.3 / 48개
	- android - 3.9 / 174개 / 1만회 이상
- 쉽고 빠른 제품 등록
	- 바코드
	- 명세표/영수증
	- 직접 입력
- 유통업체, 외식업체의 체계적인 품목 별 재고관리
	- 냉장고 추가
	- 취급 상품 (동일 상품군 관리)
- 실시간 재고 현황 공유
	- 멤버 초대
- 유통기한 임박 알림
- 사용 유형 선택
	- 일반 가정집
	- 외식업체
	- 유통업체
- http://www.ourneeds.co.kr
- https://www.wadiz.kr/web/campaign/detail/126049
- https://www.dailypop.kr/news/articleView.html?idxno=62424
### **FREEZY** - My Fridge Manager
- stores
	- iOS - 4.7 / 128명
### **원더 프리지**
- stores
	- android - 4.7 / 199개 / 1만회 이상
### **유리트 주간 식단** - 직관적인 식단 관리, AI 식단 추천
- stores
	- iOS - 4.8 / 164개
	- android - 4.9 / 190개 / 1만회 이상
### **냉장고 파먹기** - 유투브, 블로그 레시피 검색, 기록, 추천
- stores
	- iOS - 4.8 / 50개
	- android - 4.8 / 138개 / 5천회 이상
- 유통기한 관리는 기본, 냉장고 속 재료들로 자동 레시피 추천까지 해드립니다.
- 유튜브, 블로그 돌아다닐 필요없이 레시피 저장소에서 바로 검색!
- 나만의 레시피를 간단하게 메모하고 싶을 때도 레시피 저장소!
- 나의 냉장고
	- 영수증 입력
	- 재료 입력
- 냉장고 파먹기
	- 재료 기반으로 레시피 추천
- 레시피 검색
### **거꾸로 레시피**
- stores
	- iOS - 3.8 / 103명
- 식재료를 등록하면 등록한 날짜와 소비 기한을 함께 확인할 수 있다는 점이에요
- 어플 내에 등록된 재료를 활용하여 지금 당장 만들 수 있는 레시피를 알려주어요
- 재료 추가하기
	- 터치로 아이템 다중 선택
	- 추가된 날짜, 소비기한 마감, 냉동실 보관
- 요리보기
	- 현재 가진 재료로 할 수 있는 요리 레시피 목록
- 북마크
	- 레시피 북마크 가능
### **Freeasy**
- stores
	- iOS - 4.2 / 25명
	- android - 3.4 / 45개 / 1천회 이상
### **냉비서** - 우리는 왜 잘 채우는 것에만 집중하는가? 이제는 잘 비우자!
- stores
  - android - 4.1 / 19개 / 1천회 이상
- 유통기한 소비기한 관리 :
  - 유통기한이 지났다고 버려야 하는 것이 아니다! 똑똑한 소비자로서 **소비기한까지** 충분히 고려하자
- 레시피 추천으로 냉장고 비우기 :
  - 사놓고 뭘 해먹어야 할지 모른채 방치되는 재료가 없도록 있는 재료로 할 수 있는 레시피를 이용해보자
- 보관방법 처리방법 안내 :
  - 올바른 방법으로 오랫동안 신선하게 보관하여 효율적인 소비 촉진
	일반쓰레기인지 음식쓰레기인지 너무나도 헷갈리는 사람들에게 명쾌한 해답  
- 유통기한 임박 알림 :
  - 사용자가 설정한 유통기한 임박 알림 일자대로 정해진 시간에 PUSH알림 발송
- 장보기 :
  - 하나. 하나 체크하면서 장바구니에서 보관장소로 바로 이동할 수 있고, 재료를 다먹으면 장바구니로 바로 이동시킬 수 있는 편리함접기

### **냉장고 유통기한 디데이**
- stores
	- android - 4.0 / 8개 / 1천회 이상
- 냉장고 유통기한 관리 기능
	- 냉동, 냉장, 실온으로 크게 분류
	- 각 분류에서 사용자가 원하는 기준으로 세분 분류 가능
	- 메인 페이지에서는 전체 목록의 유통기한이 날짜가 적게 남은 순서대로 표시
- 레시피 제공
	- 1000가지가 넘는 레시피를 사진, 재료, 열량, 구체적 조리과정과 함께 제공
- 메모기능
	- 냉장고 앞 보드에 적어뒀던 메모를 앱에 적어둘 수 있음
### **밥타임**
- 오늘의 추천
	- 지금 가진 재료 +@ 로 만들 수 있는 음식과 레시피 소개
- 식단짜기
	- 일주일 치 식단 미리 계획
	- 음식 북마크 기능
- 장보기 메모
	- 레시피 별 필요한 물품 선택 추가
	- 직접 추가 가능
	- 장보기 메모 리스트를 체크하면, 체크한 식품이 냉장고 관리 탭으로 이동
- 냉장고 관리
	- 냉장고, 냉동실, 상온 구분
	- 신선, 보통 , 위험
- https://steemit.com/kr/@realsunny/6xndqr
### **냉장 고등어**
- stores
	- android - 3.2 / 56개 / 1천회 이상
- 냉장고에 넣은 품목관리
- 온라인 마켓과 연동하여 손쉽게 구매한 식재료를 관리
### **우리동네GS**
- stores
	- android - 3.3 / 1만개 / 500만회 이상
- 매장에서 구입한 1+1, 2+1 상품 중 하나만 가져가고 나머지는 보관
	- 기한 내 전국 어느 GS25 매장 냉장고에서나 꺼내 먹을 수 있음
- 모바일에서 구매한 행사 상품 전체 보관
- 원하는 시간/점포 지정해 도시락 예약 주문
- GS포인트 적립 시 스탬프 형성, 모이면 선물 증정
- 회원 수 - 200만명
### **우리집 냉장고** - 냉장고 속의 음식을 관리해 드립니다.
- 냉장실, 냉동실, 실온으로 구분해서 저장
- 남은 유통기한에 따라서 빨강, 초록, 파랑색으로 표시
- 유통기한이 임박하면 알림
### **이마트 냉장고 앱**
- 이마트 전자 영수증과 연동해 자동으로 목록 제공
- 유효기간 다가오면 알람
- 가족끼리 한 냉장고에 각각 등록해 목록 공유
- 모바일 전용 쿠폰 이용해 장보기 전 할인 금액 계산

**Comment by swoohooh** [comment]
@hamzzi 저희 둘이 조사한 목록을 보시고 **경쟁 제품이라고 생각되는 서비스 이름**을 적어주시면 나중에 요약 표를 만들 때 그 목록으로 진행하겠습니다.

**Comment by hamzzi** [comment]
저는 아래정도가 경쟁 재품이라고 생각됩니다.

- 냉장고 파먹기 - 유투브, 블로그 레시피 검색, 기록, 추천
- 유통기한 언제지 - 가장 쉬운 냉장고 관리
- 거꾸로 레시피
- Freeasy
- 냉장고 유통기한 디데이
- 냉비서 - 우리는 왜 잘 채우는 것에만 집중하는가? 이제는 잘 비우자!

**Comment by swoohooh** [comment]
> 저는 아래정도가 경쟁 재품이라고 생각됩니다.
> 
> * 냉장고 파먹기 - 유투브, 블로그 레시피 검색, 기록, 추천
> * 유통기한 언제지 - 가장 쉬운 냉장고 관리
> * 거꾸로 레시피
> * Freeasy
> * 냉장고 유통기한 디데이
> * 냉비서 - 우리는 왜 잘 채우는 것에만 집중하는가? 이제는 잘 비우자!

추후에 경쟁 제품으로 표 만들어서 서비스 비교 진행해보겠습니다. #12

근데 BEEP는 왜 아니라고 생각하세요??

**Comment by hamzzi** [comment]
편의점 같은 곳에서 사용하는 앱이라고 생각 했는데 가정에서도 사용하나보네요. 원하시면 추가 하시죠 😄
